name: Fullstack CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  server:
    name: Build GraphQL Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Lint and test server
        run: |
          npm run lint || echo "No lint script"
          npm test || echo "No test script"

      - name: Start server for testing (optional)
        run: node index.js &
