name: Client CI Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build React Client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the App
        run: npm run build

      - name: Run client tests (if any)
        run: npm test || echo "No tests found"
